spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201 
spring:
  profiles: dev
  application: 
    name: microserviceproject-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/   
config:
  info: dev 8201
---
server: 
  port: 8202 
spring:
  profiles: test
  application: 
    name: microserviceproject-config-client
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
config:
  info: test 8202
 

